/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/': {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  '/mod_lists': {
    get: {
      parameters: {
        query: {
          id?: parameters['rowFilter.mod_lists.id'];
          created_at?: parameters['rowFilter.mod_lists.created_at'];
          mods?: parameters['rowFilter.mod_lists.mods'];
          title?: parameters['rowFilter.mod_lists.title'];
          game_version?: parameters['rowFilter.mod_lists.game_version'];
          modloader?: parameters['rowFilter.mod_lists.modloader'];
          /** Filtering Columns */
          select?: parameters['select'];
          /** Ordering */
          order?: parameters['order'];
          /** Limiting and Pagination */
          offset?: parameters['offset'];
          /** Limiting and Pagination */
          limit?: parameters['limit'];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters['range'];
          /** Limiting and Pagination */
          'Range-Unit'?: parameters['rangeUnit'];
          /** Preference */
          Prefer?: parameters['preferCount'];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions['mod_lists'][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** mod_lists */
          mod_lists?: definitions['mod_lists'];
        };
        query: {
          /** Filtering Columns */
          select?: parameters['select'];
        };
        header: {
          /** Preference */
          Prefer?: parameters['preferReturn'];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters['rowFilter.mod_lists.id'];
          created_at?: parameters['rowFilter.mod_lists.created_at'];
          mods?: parameters['rowFilter.mod_lists.mods'];
          title?: parameters['rowFilter.mod_lists.title'];
          game_version?: parameters['rowFilter.mod_lists.game_version'];
          modloader?: parameters['rowFilter.mod_lists.modloader'];
        };
        header: {
          /** Preference */
          Prefer?: parameters['preferReturn'];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters['rowFilter.mod_lists.id'];
          created_at?: parameters['rowFilter.mod_lists.created_at'];
          mods?: parameters['rowFilter.mod_lists.mods'];
          title?: parameters['rowFilter.mod_lists.title'];
          game_version?: parameters['rowFilter.mod_lists.game_version'];
          modloader?: parameters['rowFilter.mod_lists.modloader'];
        };
        body: {
          /** mod_lists */
          mod_lists?: definitions['mod_lists'];
        };
        header: {
          /** Preference */
          Prefer?: parameters['preferReturn'];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  mod_lists: {
    /**
     * Format: text
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /** Format: json */
    mods: unknown;
    /**
     * Format: text
     * @default
     */
    title: string;
    /** Format: text */
    game_version: string;
    /** Format: text */
    modloader: string;
  };
}

export interface parameters {
  /**
   * @description Preference
   * @enum {string}
   */
  preferParams: 'params=single-object';
  /**
   * @description Preference
   * @enum {string}
   */
  preferReturn: 'return=representation' | 'return=minimal' | 'return=none';
  /**
   * @description Preference
   * @enum {string}
   */
  preferCount: 'count=none';
  /** @description Filtering Columns */
  select: string;
  /** @description On Conflict */
  on_conflict: string;
  /** @description Ordering */
  order: string;
  /** @description Limiting and Pagination */
  range: string;
  /**
   * @description Limiting and Pagination
   * @default items
   */
  rangeUnit: string;
  /** @description Limiting and Pagination */
  offset: string;
  /** @description Limiting and Pagination */
  limit: string;
  /** @description mod_lists */
  'body.mod_lists': definitions['mod_lists'];
  /** Format: text */
  'rowFilter.mod_lists.id': string;
  /** Format: timestamp with time zone */
  'rowFilter.mod_lists.created_at': string;
  /** Format: json */
  'rowFilter.mod_lists.mods': string;
  /** Format: text */
  'rowFilter.mod_lists.title': string;
  /** Format: text */
  'rowFilter.mod_lists.game_version': string;
  /** Format: text */
  'rowFilter.mod_lists.modloader': string;
}

export interface operations {}

export interface external {}
